---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-api-secrets
  namespace: default
spec:
  encryptedData:
    ALGORITHM: AgAG9Z6sec57BllQlj/KD/er0GoKMlIUyVyqYzL2t1OHRZmhws0RFjERRuywHyQbZCFcPt+nsP+YD7oUBwL53WNWjCsk5Pf9QOEUWRrCp/2B1SwcV8SPRf+qtnv/hPmaGN8wnlWxlYDUaYhnspuH27boraZyfcHoX7GMN5VgtLUHjePCh5cjOnehqHo6FpF9WuTG2FOARRUqb2SRAwJ4ifBLrLifzqMYEP4vIRD0G3DyQTPlnW2ZGaMKEVMHslJhsgixW2M8PNRDbNuIRr38783bYR4+i2sN/HWkHZz22imL8pEoBi+ff9yd2zsuFnQB5hZDlp+THhmAGwMtdJE196+IwXbGQLXZxn5AkZLBdBAuNrCgf8mn4xdUXURZMLI0aMOaSXr4J1ZoZ5vc4GdylNQHZ8HD6iR6327j1kIhiQ2WNh11F6640ny06ieJax8liaGC8IIZlQVZ/LXUAjVFlB+Me1w2WKpJLR8/mdrXQQ8cG5HfZiENMEj2G7xhUrh9j6b4sN4zz5KBnz/TcmZsptCe9FKGcCIxCGiCI0Te1+WJqHBlno3/fgG8kpz7a9S/mK1IjTOZiUTkik6c51wvUapSDiEZF5bDUXU0BPXp8vK+hdomFaQrOoqk7dHkmIMc8eOMH0rVFEGUScPNXvXsqLkH8nobzFKQOmCi6C8enLzZzM+e/D3bpjY2vYo0joFjrf2q42Ej0A==
    SECRET_KEY: AgCmGhzEg3i84XnOTF8hS6ebWojcUBflnAt7HkMQw0qTYZL+SN73ToqJmmz502hIQCstcAuRy26ew5Vz7MxX2047ntWvVT/vfGrI3Vlihee7A5JVexpg3pALRzwihsFyhDZnTFeW1h85XwdizbBjvqHaJ18IHb3Op2dlt6zoyUvzWM1+ZVyf57y4INCaMPy4I/cnNhuXn2Ei1kEvxgxg4+Z44Hb2EDfn27Gu/WWuHPTFkQ7FgIG/fAaXrN73XeuWzU21C4kk1YGgnCfHmysUiLUO15e0SN58X7ofBdqnmDAnxIMDTYc7xfmewOgmx8v2bWADLQvCG9YVEDci/AhMwZKWmw1LcHijj9kOjEGTmY8KbDftotecZeMT4qfm0zVJQFH8sbBqNiYkdspg7oAhNjGp6GtEzaxHV9OuG8iyJZB/JewgAIFN01iAiDBk8uRVJwveUxoa283cdw7swVHQi4u6i0+PqxHeGyoZULME5qbq35IBZWN4pAkrnIAYPV8eQ5xcxY/YEUGUeeS1gyGAaSIGWBokgeBH152SGUu5iTHJV/uzQwWogHybA+0a4rTkm3IV7MLMP5F2neN5dHWaUq+3j7zZEe34gfAqp6u+VDAMFth8Xc2M2uuYSXxpJL7SMED/5eXCVCLSvYSGP/vAR3qJNjJf+IacjGmqh11MuAiIT9DO9/4sHaRhslqJUPYX1kWJVJBeJtFSjnnRSRs3SWL2YOXj6MSpzk6GGyXz+zwzNZO5XMs0meFA/rPWNM2ZSNR+//Nyys6537VUXCKJquQSMw==
  template:
    metadata:
      name: auth-api-secrets
      namespace: default
