---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-api-secrets
  namespace: default
spec:
  encryptedData:
    ALGORITHM: AgBmvzKRPniOXm4KhS0Wrm6PKkUSo9opaJVH4xVxIVHGDb4Dllpt2FnEE0Fn/GzfgO9OK4x1o4Syl00IfDhEF4uxa6pXHomLcBVQHxoDQopbLUUo0O7wQn6IeBf3/1DFWDcYUT4RbttbdUP7goxI3vaunjl0aGgebGFdkukbfLLuxjPZi3s7EL4qwute8ftLpoZS1XN57oJeCXX2vWJYUeXmJsCjPH2tteHrzZBV96Gxocn/hwVzX2e3yyvXEsK3hYTg5K+VENrKHZFAQGXsaXVvwE8QgydbbSPpwVB3a7NAuwK6i0r+vAvlCi5Esap6SLZxn25kGiLZ5HEGvRxuoF7RYUumBKqVs25OB1v3HlpFdm8aHUVsxGVpAuYSmzIbDKlG4fdn75LYquZOc0McIXKO64qNFWLqKqGK9k8WQy3M+Gq9ad/AowYLrbipKx9iOMHBrbmQmpiJb8WPIvWJxj8mYoaO9e3qVxczcC5M5cghFBFhuOoVEQkeuV1+bqIN3mTSSmnsnDDGA5kkG2zVR7cpzW3o4zqY5+M9dD3wrMkDPm6d66/T59GJlq8nSc9vU0Z2lBPUpSsJF6zp6JMFXroLnJ2XixJgKaIBGhqZG2aKse485BrieE8aN7j7pBDUsP2NYyCJrloTPcF4ohJUatMzuKy709DmaWsdq1m0hpDCT2ER8Z6/Gu6jxgQpErlU22l2BIkRpQ==
    SECRET_KEY: AgApgwY/LaC80W9suKOf6/S6KxzI1XYfcbd4v9ng2AqdMSHoSBlEBIf3XPz1b6YP+dptmvqMdRTZw9g07Kb9v4e3tVDmNKnDcEGwgkl36qjppuYJfQHhdhrPyAWzDhks5XGVFLpfcJQQuTCRWgJNy70rnsiZP566Gix4zYvZFh3shpDVsHoD9PsdHc4Eu48pKVSOPkWD2dbVKgVyW1k/Grnw5ENTsvVj5+b3bZTbc20gFnQ/xyMZdu7PnNOOTsNlXMb2sDqj+sS0siV1KTD4C+IPFwCg1mjCe1XH3rPAXd+UqMh5737P3cv1+YK+dWlW05t1TpOwvwgMnNVWtw95crgv8gOVXVMnig4QxrFc40+q62jn4wrwKlJck5m9f0EusIAoI8Q57NMsyvNyOUKCyf4IXm6GkdnP+c5lXKnYciB0pFMsWjmKMhNjXNmdYWWggeKaF3+R7HhOc6v2X8OkYyfMpy7DPj/s0reakBnAPuu9/dYNVxb9h7UB//La3igC2y1I3K1ZqdT/d4iSpudsvb+8F4nVEn+7OuGRyAZXTPHaHUuOu4G0ZSBnHaAqroGO/SJInuQ+/1NhgLhvyxLIBCmhJO0MyazxEigfk77nqQAWzj1y07sFYj1nFdMqSbCvaw6nFWgqIl+sFamr4+7Q4bxtmon8dmHGZl8vN+jzzKLzOixQZj59qzXwX0mNGOp6dhdRAUkZWEpW7rw4E1I1d2yxsol/eJ1Wd2+hS80LQ2C3kDW/1R/lRrdd4AlmxqmkNJOBuvkK03ImOoPvgpTvLSFkQw==
  template:
    metadata:
      name: auth-api-secrets
      namespace: default
