---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-api-secrets
  namespace: default
spec:
  encryptedData:
    ALGORITHM: AgAyBnL+mWukcOPMvgk4JE78NB/P5xsOZu5loVM09ggk+lvQtq92V2FDv0DF+rqItP6fXjlu2uP7mWCGDkRWuqTKEGVMy44TRMKYpAXvmclkV27KQV30R6I6HZW5n5nev8PNs0dN/Nb4BXNuWYYn0lxq63AtJ2l8xlNWI2CfxCWoS5tDJTRBiwlxI09r2f5ob+UYXXDCNT3aUzyhDLLf+rKMOzh4k191rVjy8sa3mLoZqmkryGaVBnEtIttuy6TfaT5e+mGCDdYod+REEAPy0DAahUgDhRkqRX68p5cjVwPYl2pLhDN7mN97W30a0CLTj/ALYU3QlvUHbGNCKIonMIx0fSpyjRh7PftK1Rd4f/XQ9ia96hHx4KaYvPYho3n7yI/bWCX6cEvcqcHgeIGL0uKGzqDR0obhQimbnUy0t7U9WT+kKUMUKkjtAJqZl4U1MTPKdPVAwzhGyQpi6RHV6uQRZARmB9RzDKtjpTM8L59JY0CgG/nZrbXzENt8fLROQpY29GVsW9hm8BBJhuuip9MzX4RBaJmvgPqeHvay/i67gGiXZBncUdz4DS0Ek/bP80Ni/HHx4dK9f/VmBAdjmr1u+UEB7iAExOHsUrL+yDHMLdK12S5k3DMftc56Erk/CUguQBx3XRQDUNpg09F7sK3qV5KOsccwP43KLpQE6S/SGoXmY8PB9wfJQ/WeFlCT7+5vJ0akdQ==
    SECRET_KEY: AgCH+HbXxkY7EY29N4ThZpPxngFYSG5zbiUpbpntNEzhZkwB6KTydPrPUUvVp7IxkjPFJn6RmCEKzqXb54gPEQ50ks8NJFeq+Xz6wOZDDeVW3BAS3zzwzA+P1m4XpFtkYIHfuLl7C/g3/EMFZzPTt33eDIZbpuJ/gXvAXyDyqWYm4Z2Mn3WY9cXWL/oRsSy3K6xGKYsTyssQ3bIqe2oVMwMhko1Juxpkmvz8RyRPz6hkYjY/VaLlxtqCF4PfLfuFb276yPEL3jQiiV6HRuV6DOybq9+iYI+5XLpFnpfgrikYEGPCJ81Kyn9nuTMoV6PPqMsJFpG9noOBm15cm2nmYCjKQ3rKL3X18tilz7ytaoYIyzzPlyaeIIV7UOkjLd40JUhqp5vBSuW2Auad3SeY/KfkzgfXL2FM31yKXU0pjOvykRKmfqbUmhCYVP8MnsCOIviqL6TV7XIsAtsJZm8huBjdBY1S6pikU1jwV45Cd2FUcjxTES+udFUj+unHjR9L10YYvnmzS/XpW9X+gxIK7rXkwi1hxKyDdzFbuVYG1RgRVUYwmr67P6ECtypSoYgPeakRLtfu3fctR9EG7HADtkdDvxkmggdp8ui3PlBllDBEDP5SyidHXtkdphZbROIXnTV+YCUlBEGV8FI+NPVtZ3NTEQ0f+IdI+1o3SeUwrEze0vH5jdwKBWmJwKzB0vCCdReoMjcPX9XuwNOxE0UWXpKYCKmTahuOs06BZ/BOvhtbxDyM+Z1Oktdgo0mdki/vNoBj0L+IFQe4pHy0Ivxb6FI9aQ==
  template:
    metadata:
      name: auth-api-secrets
      namespace: default
