apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-api
spec:
  selector:
    matchLabels:
      app: comment-api
  template:
    metadata:
      labels:
        app: comment-api
    spec:
      containers:
      - name: comment-api
        image: comment-api:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

        readinessProbe:
          httpGet:
            path: health   # Much lighter than /read_all_users
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5  # Check every 5s during the stress test
          failureThreshold: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20

        resources:
          requests:
            cpu: "200m"   # 10% of a CPU core
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        env:

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: SECRET_KEY
        
        - name: ALGORITHM
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: ALGORITHM

        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: POSTGRES_DB_NAME
        # Constructing the URL: comment-db is the service name from comment-db.yaml
        - name: COMMENT_DATABASE_URL
          value: "postgresql+asyncpg://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@comment-db:5432/$(POSTGRES_DB_NAME)"
---
apiVersion: v1
kind: Service
metadata:
  name: comment-api
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: comment-api