apiVersion: batch/v1
kind: Job
metadata:
  name: comment-db-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: comment-api:local
        command: ["alembic", "upgrade", "head"]
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: POSTGRES_USERNAME
              
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: comment-api-secrets
              key: POSTGRES_DB_NAME

        - name: COMMENT_DATABASE_URL
          value: "postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@comment-db:5432/$(POSTGRES_DB)"
      restartPolicy: OnFailure
  backoffLimit: 4