apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: post-db-pv
  resources:
    requests:
      storage: 5Gi # Change this based on your data needs