apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      
      # --- USER API ROUTE ---
      - path: /user(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-api
            port:
              number: 80
      
      # --- POST API ROUTE ---
      - path: /post(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: post-api
            port:
              number: 80
      
      # --- COMMENT API ROUTE ---
      - path: /comment(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: comment-api
            port:
              number: 80
      
      # --- AUTH API ROUTE ---
      - path: /auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-api
            port:
              number: 80