apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api
spec:
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      initContainers:
      - name: db-migration
        image: post-api:local
        imagePullPolicy: Never
        command: ["alembic", "upgrade", "head"]
        env:

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_DB_NAME
              
        - name: DATABASE_URL
          value: "postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@post-db:5432/$(POSTGRES_DB)"
      # --- End of InitContainer ---
      
      containers:
      - name: post-api
        image: post-api:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"   # 10% of a CPU core
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: SECRET_KEY
        
        - name: ALGORITHM
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: ALGORITHM

        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_DB_NAME
        # Constructing the URL: post-db is the service name from post-db.yaml
        - name: DATABASE_URL
          value: "postgresql+asyncpg://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@post-db:5432/$(POSTGRES_DB_NAME)"
---
apiVersion: v1
kind: Service
metadata:
  name: post-api
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: post-api