apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api
spec:
  replicas: 1 # replicas is managed by HPA, so we start with 1
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
      - name: post-api
        image: ghcr.io/MicroServices-SocialApp/All_MicroServices/Post-API:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"   # 10% of a CPU core
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:

        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_DB_NAME
        # Constructing the URL: post-db is the service name from post-db.yaml
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@post-db:5432/$(POSTGRES_DB_NAME)"
---
apiVersion: v1
kind: Service
metadata:
  name: post-api
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: post-api