apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api
spec:
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:      
      containers:
      - name: post-api
        image: post-api:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

        readinessProbe:
          httpGet:
            path: health   # Much lighter than /read_all_users
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5  # Check every 5s during the stress test
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20

        resources:
          requests:
            cpu: "100m"   # 10% of a CPU core
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: SECRET_KEY
        
        - name: ALGORITHM
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: ALGORITHM

        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: post-api-secrets
              key: POSTGRES_DB_NAME
        # Constructing the URL: post-db is the service name from post-db.yaml
        - name: DATABASE_URL
          value: "postgresql+asyncpg://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@post-db:5432/$(POSTGRES_DB_NAME)"
---
apiVersion: v1
kind: Service
metadata:
  name: post-api
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: post-api